I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    show rabblock_normal right
Exception: Image 'rabblock_normal' does not accept attributes 'right'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    show rabblock_normal right
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.0.3-sdk\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-8.0.3-sdk\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-8.0.3-sdk\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "D:\renpy-8.0.3-sdk\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'rabblock_normal' does not accept attributes 'right'.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
WSMS_pleasework 1.0
Tue Oct 18 17:43:17 2022
