I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 157, in script
    bbun "Oh I’ll (__show__) him!! He’s totally going to get (__kicked__) out of the (__manor__)  when it’s in my name!"
Exception: Sayer 'bbun' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 157, in script
    bbun "Oh I’ll (__show__) him!! He’s totally going to get (__kicked__) out of the (__manor__)  when it’s in my name!"
  File "C:\Users\1023789\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\1023789\Desktop\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'bbun' is not defined.

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
WSMS_pleasework 1.0
Wed Oct 12 14:24:39 2022
